### ISSUE TITLE
Can't use with d-none helper because of css cascade 

### ISSUE THREAD

**Issue by stalker3343** [andrejsharapov/vuetify-css-extensions#1]
![изображение](https://user-images.githubusercontent.com/42894422/173296216-8f75e1eb-cf79-42eb-83c2-c0627735b370.png)

d-none from vuetify go before d-grid from my styles. So d-grid on md don't work. 

Using nuxt and nuxt vuetify module. Add styles in css in nuxt.config

**Comment by andrejsharapov** [comment]
Thx! This has been fixed.
